package com.agung.agungtesting.domain;

import java.io.Serializable;

public class Customer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String nama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.bank
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.rekening
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String rekening;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.iban_code
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String ibanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id_pengguna
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Integer idPengguna;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.nama
     *
     * @return the value of customer.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.nama
     *
     * @param nama the value for customer.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setNama(String nama) {
        this.nama = nama == null ? null : nama.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.bank
     *
     * @return the value of customer.bank
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.bank
     *
     * @param bank the value for customer.bank
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.rekening
     *
     * @return the value of customer.rekening
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getRekening() {
        return rekening;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.rekening
     *
     * @param rekening the value for customer.rekening
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setRekening(String rekening) {
        this.rekening = rekening == null ? null : rekening.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.iban_code
     *
     * @return the value of customer.iban_code
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getIbanCode() {
        return ibanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.iban_code
     *
     * @param ibanCode the value for customer.iban_code
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setIbanCode(String ibanCode) {
        this.ibanCode = ibanCode == null ? null : ibanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id_pengguna
     *
     * @return the value of customer.id_pengguna
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Integer getIdPengguna() {
        return idPengguna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id_pengguna
     *
     * @param idPengguna the value for customer.id_pengguna
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setIdPengguna(Integer idPengguna) {
        this.idPengguna = idPengguna;
    }
}