package com.agung.agungtesting.domain;

import java.io.Serializable;
import java.util.Date;

public class Pengguna implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.created_at
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.updated_at
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.email
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String nama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.password
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.username
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.tanggal_lahir
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Date tanggalLahir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.ktp_id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String ktpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna.ktp_lokasi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String ktpLokasi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pengguna
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.id
     *
     * @return the value of pengguna.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.id
     *
     * @param id the value for pengguna.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.created_at
     *
     * @return the value of pengguna.created_at
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.created_at
     *
     * @param createdAt the value for pengguna.created_at
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.updated_at
     *
     * @return the value of pengguna.updated_at
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.updated_at
     *
     * @param updatedAt the value for pengguna.updated_at
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.email
     *
     * @return the value of pengguna.email
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.email
     *
     * @param email the value for pengguna.email
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.nama
     *
     * @return the value of pengguna.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.nama
     *
     * @param nama the value for pengguna.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setNama(String nama) {
        this.nama = nama == null ? null : nama.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.password
     *
     * @return the value of pengguna.password
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.password
     *
     * @param password the value for pengguna.password
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.username
     *
     * @return the value of pengguna.username
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.username
     *
     * @param username the value for pengguna.username
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.tanggal_lahir
     *
     * @return the value of pengguna.tanggal_lahir
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Date getTanggalLahir() {
        return tanggalLahir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.tanggal_lahir
     *
     * @param tanggalLahir the value for pengguna.tanggal_lahir
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setTanggalLahir(Date tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.ktp_id
     *
     * @return the value of pengguna.ktp_id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getKtpId() {
        return ktpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.ktp_id
     *
     * @param ktpId the value for pengguna.ktp_id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setKtpId(String ktpId) {
        this.ktpId = ktpId == null ? null : ktpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna.ktp_lokasi
     *
     * @return the value of pengguna.ktp_lokasi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getKtpLokasi() {
        return ktpLokasi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna.ktp_lokasi
     *
     * @param ktpLokasi the value for pengguna.ktp_lokasi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setKtpLokasi(String ktpLokasi) {
        this.ktpLokasi = ktpLokasi == null ? null : ktpLokasi.trim();
    }
}