package com.agung.agungtesting.domain;

import java.io.Serializable;
import java.util.Date;

public class Transaksi implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.waktu_transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Date waktuTransaksi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.id_penerima
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Integer idPenerima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.id_pengirim
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Integer idPengirim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.kurs_dari
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String kursDari;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.kurs_ke
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String kursKe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.kurs
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Double kurs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.status
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.promo_id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Integer promoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.nominal
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Long nominal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaksi.kurs_idr
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Double kursIdr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.id
     *
     * @return the value of transaksi.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.id
     *
     * @param id the value for transaksi.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.waktu_transaksi
     *
     * @return the value of transaksi.waktu_transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Date getWaktuTransaksi() {
        return waktuTransaksi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.waktu_transaksi
     *
     * @param waktuTransaksi the value for transaksi.waktu_transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setWaktuTransaksi(Date waktuTransaksi) {
        this.waktuTransaksi = waktuTransaksi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.id_penerima
     *
     * @return the value of transaksi.id_penerima
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Integer getIdPenerima() {
        return idPenerima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.id_penerima
     *
     * @param idPenerima the value for transaksi.id_penerima
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setIdPenerima(Integer idPenerima) {
        this.idPenerima = idPenerima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.id_pengirim
     *
     * @return the value of transaksi.id_pengirim
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Integer getIdPengirim() {
        return idPengirim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.id_pengirim
     *
     * @param idPengirim the value for transaksi.id_pengirim
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setIdPengirim(Integer idPengirim) {
        this.idPengirim = idPengirim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.kurs_dari
     *
     * @return the value of transaksi.kurs_dari
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getKursDari() {
        return kursDari;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.kurs_dari
     *
     * @param kursDari the value for transaksi.kurs_dari
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setKursDari(String kursDari) {
        this.kursDari = kursDari == null ? null : kursDari.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.kurs_ke
     *
     * @return the value of transaksi.kurs_ke
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getKursKe() {
        return kursKe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.kurs_ke
     *
     * @param kursKe the value for transaksi.kurs_ke
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setKursKe(String kursKe) {
        this.kursKe = kursKe == null ? null : kursKe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.kurs
     *
     * @return the value of transaksi.kurs
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Double getKurs() {
        return kurs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.kurs
     *
     * @param kurs the value for transaksi.kurs
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setKurs(Double kurs) {
        this.kurs = kurs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.status
     *
     * @return the value of transaksi.status
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.status
     *
     * @param status the value for transaksi.status
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.promo_id
     *
     * @return the value of transaksi.promo_id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Integer getPromoId() {
        return promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.promo_id
     *
     * @param promoId the value for transaksi.promo_id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setPromoId(Integer promoId) {
        this.promoId = promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.nominal
     *
     * @return the value of transaksi.nominal
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Long getNominal() {
        return nominal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.nominal
     *
     * @param nominal the value for transaksi.nominal
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setNominal(Long nominal) {
        this.nominal = nominal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaksi.kurs_idr
     *
     * @return the value of transaksi.kurs_idr
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Double getKursIdr() {
        return kursIdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaksi.kurs_idr
     *
     * @param kursIdr the value for transaksi.kurs_idr
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setKursIdr(Double kursIdr) {
        this.kursIdr = kursIdr;
    }
}