package com.agung.agungtesting.dao;

import com.agung.agungtesting.domain.PenggunaPeran;
import com.agung.agungtesting.domain.PenggunaPeranExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PenggunaPeranMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    long countByExample(PenggunaPeranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int deleteByExample(PenggunaPeranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int deleteByPrimaryKey(@Param("idPengguna") Long idPengguna, @Param("idPeran") Long idPeran);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int insert(PenggunaPeran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int insertSelective(PenggunaPeran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    List<PenggunaPeran> selectByExampleWithRowbounds(PenggunaPeranExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    List<PenggunaPeran> selectByExample(PenggunaPeranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByExampleSelective(@Param("record") PenggunaPeran record, @Param("example") PenggunaPeranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByExample(@Param("record") PenggunaPeran record, @Param("example") PenggunaPeranExample example);
}