package com.agung.agungtesting.dao;

import com.agung.agungtesting.domain.Promo;
import com.agung.agungtesting.domain.PromoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PromoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    long countByExample(PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int deleteByExample(PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int insert(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int insertSelective(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    List<Promo> selectByExampleWithRowbounds(PromoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    List<Promo> selectByExample(PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    Promo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByExampleSelective(@Param("record") Promo record, @Param("example") PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByExample(@Param("record") Promo record, @Param("example") PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByPrimaryKeySelective(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByPrimaryKey(Promo record);
}