package com.agung.agungtesting.dao;

import com.agung.agungtesting.domain.Transaksi;
import com.agung.agungtesting.domain.TransaksiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TransaksiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    long countByExample(TransaksiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int deleteByExample(TransaksiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int insert(Transaksi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int insertSelective(Transaksi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    List<Transaksi> selectByExampleWithRowbounds(TransaksiExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    List<Transaksi> selectByExample(TransaksiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    Transaksi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByExampleSelective(@Param("record") Transaksi record, @Param("example") TransaksiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByExample(@Param("record") Transaksi record, @Param("example") TransaksiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByPrimaryKeySelective(Transaksi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    int updateByPrimaryKey(Transaksi record);
}