package com.agung.agungtesting.domain;

import java.io.Serializable;

public class PenggunaPeran implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna_peran.id_pengguna
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Long idPengguna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pengguna_peran.id_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Long idPeran;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pengguna_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna_peran.id_pengguna
     *
     * @return the value of pengguna_peran.id_pengguna
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Long getIdPengguna() {
        return idPengguna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna_peran.id_pengguna
     *
     * @param idPengguna the value for pengguna_peran.id_pengguna
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setIdPengguna(Long idPengguna) {
        this.idPengguna = idPengguna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pengguna_peran.id_peran
     *
     * @return the value of pengguna_peran.id_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Long getIdPeran() {
        return idPeran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pengguna_peran.id_peran
     *
     * @param idPeran the value for pengguna_peran.id_peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setIdPeran(Long idPeran) {
        this.idPeran = idPeran;
    }
}