package com.agung.agungtesting.domain;

import java.io.Serializable;

public class Peran implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peran.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peran.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private String nama;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table peran
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peran.id
     *
     * @return the value of peran.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peran.id
     *
     * @param id the value for peran.id
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peran.nama
     *
     * @return the value of peran.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peran.nama
     *
     * @param nama the value for peran.nama
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setNama(String nama) {
        this.nama = nama == null ? null : nama.trim();
    }
}