package com.agung.agungtesting.domain;

import java.util.ArrayList;
import java.util.List;

public class PromoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public PromoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNamaIsNull() {
            addCriterion("nama is null");
            return (Criteria) this;
        }

        public Criteria andNamaIsNotNull() {
            addCriterion("nama is not null");
            return (Criteria) this;
        }

        public Criteria andNamaEqualTo(String value) {
            addCriterion("nama =", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotEqualTo(String value) {
            addCriterion("nama <>", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThan(String value) {
            addCriterion("nama >", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThanOrEqualTo(String value) {
            addCriterion("nama >=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThan(String value) {
            addCriterion("nama <", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThanOrEqualTo(String value) {
            addCriterion("nama <=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLike(String value) {
            addCriterion("nama like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotLike(String value) {
            addCriterion("nama not like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaIn(List<String> values) {
            addCriterion("nama in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotIn(List<String> values) {
            addCriterion("nama not in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaBetween(String value1, String value2) {
            addCriterion("nama between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotBetween(String value1, String value2) {
            addCriterion("nama not between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andKursIsNull() {
            addCriterion("kurs is null");
            return (Criteria) this;
        }

        public Criteria andKursIsNotNull() {
            addCriterion("kurs is not null");
            return (Criteria) this;
        }

        public Criteria andKursEqualTo(Double value) {
            addCriterion("kurs =", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursNotEqualTo(Double value) {
            addCriterion("kurs <>", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursGreaterThan(Double value) {
            addCriterion("kurs >", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursGreaterThanOrEqualTo(Double value) {
            addCriterion("kurs >=", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursLessThan(Double value) {
            addCriterion("kurs <", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursLessThanOrEqualTo(Double value) {
            addCriterion("kurs <=", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursIn(List<Double> values) {
            addCriterion("kurs in", values, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursNotIn(List<Double> values) {
            addCriterion("kurs not in", values, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursBetween(Double value1, Double value2) {
            addCriterion("kurs between", value1, value2, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursNotBetween(Double value1, Double value2) {
            addCriterion("kurs not between", value1, value2, "kurs");
            return (Criteria) this;
        }

        public Criteria andNominalIsNull() {
            addCriterion("nominal is null");
            return (Criteria) this;
        }

        public Criteria andNominalIsNotNull() {
            addCriterion("nominal is not null");
            return (Criteria) this;
        }

        public Criteria andNominalEqualTo(Integer value) {
            addCriterion("nominal =", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotEqualTo(Integer value) {
            addCriterion("nominal <>", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalGreaterThan(Integer value) {
            addCriterion("nominal >", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalGreaterThanOrEqualTo(Integer value) {
            addCriterion("nominal >=", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalLessThan(Integer value) {
            addCriterion("nominal <", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalLessThanOrEqualTo(Integer value) {
            addCriterion("nominal <=", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalIn(List<Integer> values) {
            addCriterion("nominal in", values, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotIn(List<Integer> values) {
            addCriterion("nominal not in", values, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalBetween(Integer value1, Integer value2) {
            addCriterion("nominal between", value1, value2, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotBetween(Integer value1, Integer value2) {
            addCriterion("nominal not between", value1, value2, "nominal");
            return (Criteria) this;
        }

        public Criteria andTipeIsNull() {
            addCriterion("tipe is null");
            return (Criteria) this;
        }

        public Criteria andTipeIsNotNull() {
            addCriterion("tipe is not null");
            return (Criteria) this;
        }

        public Criteria andTipeEqualTo(Integer value) {
            addCriterion("tipe =", value, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeNotEqualTo(Integer value) {
            addCriterion("tipe <>", value, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeGreaterThan(Integer value) {
            addCriterion("tipe >", value, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeGreaterThanOrEqualTo(Integer value) {
            addCriterion("tipe >=", value, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeLessThan(Integer value) {
            addCriterion("tipe <", value, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeLessThanOrEqualTo(Integer value) {
            addCriterion("tipe <=", value, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeIn(List<Integer> values) {
            addCriterion("tipe in", values, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeNotIn(List<Integer> values) {
            addCriterion("tipe not in", values, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeBetween(Integer value1, Integer value2) {
            addCriterion("tipe between", value1, value2, "tipe");
            return (Criteria) this;
        }

        public Criteria andTipeNotBetween(Integer value1, Integer value2) {
            addCriterion("tipe not between", value1, value2, "tipe");
            return (Criteria) this;
        }

        public Criteria andKursDariIsNull() {
            addCriterion("kurs_dari is null");
            return (Criteria) this;
        }

        public Criteria andKursDariIsNotNull() {
            addCriterion("kurs_dari is not null");
            return (Criteria) this;
        }

        public Criteria andKursDariEqualTo(String value) {
            addCriterion("kurs_dari =", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariNotEqualTo(String value) {
            addCriterion("kurs_dari <>", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariGreaterThan(String value) {
            addCriterion("kurs_dari >", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariGreaterThanOrEqualTo(String value) {
            addCriterion("kurs_dari >=", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariLessThan(String value) {
            addCriterion("kurs_dari <", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariLessThanOrEqualTo(String value) {
            addCriterion("kurs_dari <=", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariLike(String value) {
            addCriterion("kurs_dari like", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariNotLike(String value) {
            addCriterion("kurs_dari not like", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariIn(List<String> values) {
            addCriterion("kurs_dari in", values, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariNotIn(List<String> values) {
            addCriterion("kurs_dari not in", values, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariBetween(String value1, String value2) {
            addCriterion("kurs_dari between", value1, value2, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariNotBetween(String value1, String value2) {
            addCriterion("kurs_dari not between", value1, value2, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursKeIsNull() {
            addCriterion("kurs_ke is null");
            return (Criteria) this;
        }

        public Criteria andKursKeIsNotNull() {
            addCriterion("kurs_ke is not null");
            return (Criteria) this;
        }

        public Criteria andKursKeEqualTo(String value) {
            addCriterion("kurs_ke =", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeNotEqualTo(String value) {
            addCriterion("kurs_ke <>", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeGreaterThan(String value) {
            addCriterion("kurs_ke >", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeGreaterThanOrEqualTo(String value) {
            addCriterion("kurs_ke >=", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeLessThan(String value) {
            addCriterion("kurs_ke <", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeLessThanOrEqualTo(String value) {
            addCriterion("kurs_ke <=", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeLike(String value) {
            addCriterion("kurs_ke like", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeNotLike(String value) {
            addCriterion("kurs_ke not like", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeIn(List<String> values) {
            addCriterion("kurs_ke in", values, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeNotIn(List<String> values) {
            addCriterion("kurs_ke not in", values, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeBetween(String value1, String value2) {
            addCriterion("kurs_ke between", value1, value2, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeNotBetween(String value1, String value2) {
            addCriterion("kurs_ke not between", value1, value2, "kursKe");
            return (Criteria) this;
        }

        public Criteria andAktifIsNull() {
            addCriterion("aktif is null");
            return (Criteria) this;
        }

        public Criteria andAktifIsNotNull() {
            addCriterion("aktif is not null");
            return (Criteria) this;
        }

        public Criteria andAktifEqualTo(Boolean value) {
            addCriterion("aktif =", value, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifNotEqualTo(Boolean value) {
            addCriterion("aktif <>", value, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifGreaterThan(Boolean value) {
            addCriterion("aktif >", value, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifGreaterThanOrEqualTo(Boolean value) {
            addCriterion("aktif >=", value, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifLessThan(Boolean value) {
            addCriterion("aktif <", value, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifLessThanOrEqualTo(Boolean value) {
            addCriterion("aktif <=", value, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifIn(List<Boolean> values) {
            addCriterion("aktif in", values, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifNotIn(List<Boolean> values) {
            addCriterion("aktif not in", values, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifBetween(Boolean value1, Boolean value2) {
            addCriterion("aktif between", value1, value2, "aktif");
            return (Criteria) this;
        }

        public Criteria andAktifNotBetween(Boolean value1, Boolean value2) {
            addCriterion("aktif not between", value1, value2, "aktif");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table promo
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 02 02:49:41 ICT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table promo
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}