package com.agung.agungtesting.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransaksiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public TransaksiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiIsNull() {
            addCriterion("waktu_transaksi is null");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiIsNotNull() {
            addCriterion("waktu_transaksi is not null");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiEqualTo(Date value) {
            addCriterion("waktu_transaksi =", value, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiNotEqualTo(Date value) {
            addCriterion("waktu_transaksi <>", value, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiGreaterThan(Date value) {
            addCriterion("waktu_transaksi >", value, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiGreaterThanOrEqualTo(Date value) {
            addCriterion("waktu_transaksi >=", value, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiLessThan(Date value) {
            addCriterion("waktu_transaksi <", value, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiLessThanOrEqualTo(Date value) {
            addCriterion("waktu_transaksi <=", value, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiIn(List<Date> values) {
            addCriterion("waktu_transaksi in", values, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiNotIn(List<Date> values) {
            addCriterion("waktu_transaksi not in", values, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiBetween(Date value1, Date value2) {
            addCriterion("waktu_transaksi between", value1, value2, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andWaktuTransaksiNotBetween(Date value1, Date value2) {
            addCriterion("waktu_transaksi not between", value1, value2, "waktuTransaksi");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaIsNull() {
            addCriterion("id_penerima is null");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaIsNotNull() {
            addCriterion("id_penerima is not null");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaEqualTo(Integer value) {
            addCriterion("id_penerima =", value, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaNotEqualTo(Integer value) {
            addCriterion("id_penerima <>", value, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaGreaterThan(Integer value) {
            addCriterion("id_penerima >", value, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_penerima >=", value, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaLessThan(Integer value) {
            addCriterion("id_penerima <", value, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaLessThanOrEqualTo(Integer value) {
            addCriterion("id_penerima <=", value, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaIn(List<Integer> values) {
            addCriterion("id_penerima in", values, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaNotIn(List<Integer> values) {
            addCriterion("id_penerima not in", values, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaBetween(Integer value1, Integer value2) {
            addCriterion("id_penerima between", value1, value2, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPenerimaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_penerima not between", value1, value2, "idPenerima");
            return (Criteria) this;
        }

        public Criteria andIdPengirimIsNull() {
            addCriterion("id_pengirim is null");
            return (Criteria) this;
        }

        public Criteria andIdPengirimIsNotNull() {
            addCriterion("id_pengirim is not null");
            return (Criteria) this;
        }

        public Criteria andIdPengirimEqualTo(Integer value) {
            addCriterion("id_pengirim =", value, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimNotEqualTo(Integer value) {
            addCriterion("id_pengirim <>", value, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimGreaterThan(Integer value) {
            addCriterion("id_pengirim >", value, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_pengirim >=", value, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimLessThan(Integer value) {
            addCriterion("id_pengirim <", value, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimLessThanOrEqualTo(Integer value) {
            addCriterion("id_pengirim <=", value, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimIn(List<Integer> values) {
            addCriterion("id_pengirim in", values, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimNotIn(List<Integer> values) {
            addCriterion("id_pengirim not in", values, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimBetween(Integer value1, Integer value2) {
            addCriterion("id_pengirim between", value1, value2, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andIdPengirimNotBetween(Integer value1, Integer value2) {
            addCriterion("id_pengirim not between", value1, value2, "idPengirim");
            return (Criteria) this;
        }

        public Criteria andKursDariIsNull() {
            addCriterion("kurs_dari is null");
            return (Criteria) this;
        }

        public Criteria andKursDariIsNotNull() {
            addCriterion("kurs_dari is not null");
            return (Criteria) this;
        }

        public Criteria andKursDariEqualTo(String value) {
            addCriterion("kurs_dari =", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariNotEqualTo(String value) {
            addCriterion("kurs_dari <>", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariGreaterThan(String value) {
            addCriterion("kurs_dari >", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariGreaterThanOrEqualTo(String value) {
            addCriterion("kurs_dari >=", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariLessThan(String value) {
            addCriterion("kurs_dari <", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariLessThanOrEqualTo(String value) {
            addCriterion("kurs_dari <=", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariLike(String value) {
            addCriterion("kurs_dari like", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariNotLike(String value) {
            addCriterion("kurs_dari not like", value, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariIn(List<String> values) {
            addCriterion("kurs_dari in", values, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariNotIn(List<String> values) {
            addCriterion("kurs_dari not in", values, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariBetween(String value1, String value2) {
            addCriterion("kurs_dari between", value1, value2, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursDariNotBetween(String value1, String value2) {
            addCriterion("kurs_dari not between", value1, value2, "kursDari");
            return (Criteria) this;
        }

        public Criteria andKursKeIsNull() {
            addCriterion("kurs_ke is null");
            return (Criteria) this;
        }

        public Criteria andKursKeIsNotNull() {
            addCriterion("kurs_ke is not null");
            return (Criteria) this;
        }

        public Criteria andKursKeEqualTo(String value) {
            addCriterion("kurs_ke =", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeNotEqualTo(String value) {
            addCriterion("kurs_ke <>", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeGreaterThan(String value) {
            addCriterion("kurs_ke >", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeGreaterThanOrEqualTo(String value) {
            addCriterion("kurs_ke >=", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeLessThan(String value) {
            addCriterion("kurs_ke <", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeLessThanOrEqualTo(String value) {
            addCriterion("kurs_ke <=", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeLike(String value) {
            addCriterion("kurs_ke like", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeNotLike(String value) {
            addCriterion("kurs_ke not like", value, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeIn(List<String> values) {
            addCriterion("kurs_ke in", values, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeNotIn(List<String> values) {
            addCriterion("kurs_ke not in", values, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeBetween(String value1, String value2) {
            addCriterion("kurs_ke between", value1, value2, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursKeNotBetween(String value1, String value2) {
            addCriterion("kurs_ke not between", value1, value2, "kursKe");
            return (Criteria) this;
        }

        public Criteria andKursIsNull() {
            addCriterion("kurs is null");
            return (Criteria) this;
        }

        public Criteria andKursIsNotNull() {
            addCriterion("kurs is not null");
            return (Criteria) this;
        }

        public Criteria andKursEqualTo(Double value) {
            addCriterion("kurs =", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursNotEqualTo(Double value) {
            addCriterion("kurs <>", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursGreaterThan(Double value) {
            addCriterion("kurs >", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursGreaterThanOrEqualTo(Double value) {
            addCriterion("kurs >=", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursLessThan(Double value) {
            addCriterion("kurs <", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursLessThanOrEqualTo(Double value) {
            addCriterion("kurs <=", value, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursIn(List<Double> values) {
            addCriterion("kurs in", values, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursNotIn(List<Double> values) {
            addCriterion("kurs not in", values, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursBetween(Double value1, Double value2) {
            addCriterion("kurs between", value1, value2, "kurs");
            return (Criteria) this;
        }

        public Criteria andKursNotBetween(Double value1, Double value2) {
            addCriterion("kurs not between", value1, value2, "kurs");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPromoIdIsNull() {
            addCriterion("promo_id is null");
            return (Criteria) this;
        }

        public Criteria andPromoIdIsNotNull() {
            addCriterion("promo_id is not null");
            return (Criteria) this;
        }

        public Criteria andPromoIdEqualTo(Integer value) {
            addCriterion("promo_id =", value, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdNotEqualTo(Integer value) {
            addCriterion("promo_id <>", value, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdGreaterThan(Integer value) {
            addCriterion("promo_id >", value, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("promo_id >=", value, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdLessThan(Integer value) {
            addCriterion("promo_id <", value, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdLessThanOrEqualTo(Integer value) {
            addCriterion("promo_id <=", value, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdIn(List<Integer> values) {
            addCriterion("promo_id in", values, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdNotIn(List<Integer> values) {
            addCriterion("promo_id not in", values, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdBetween(Integer value1, Integer value2) {
            addCriterion("promo_id between", value1, value2, "promoId");
            return (Criteria) this;
        }

        public Criteria andPromoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("promo_id not between", value1, value2, "promoId");
            return (Criteria) this;
        }

        public Criteria andNominalIsNull() {
            addCriterion("nominal is null");
            return (Criteria) this;
        }

        public Criteria andNominalIsNotNull() {
            addCriterion("nominal is not null");
            return (Criteria) this;
        }

        public Criteria andNominalEqualTo(Long value) {
            addCriterion("nominal =", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotEqualTo(Long value) {
            addCriterion("nominal <>", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalGreaterThan(Long value) {
            addCriterion("nominal >", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalGreaterThanOrEqualTo(Long value) {
            addCriterion("nominal >=", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalLessThan(Long value) {
            addCriterion("nominal <", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalLessThanOrEqualTo(Long value) {
            addCriterion("nominal <=", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalIn(List<Long> values) {
            addCriterion("nominal in", values, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotIn(List<Long> values) {
            addCriterion("nominal not in", values, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalBetween(Long value1, Long value2) {
            addCriterion("nominal between", value1, value2, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotBetween(Long value1, Long value2) {
            addCriterion("nominal not between", value1, value2, "nominal");
            return (Criteria) this;
        }

        public Criteria andKursIdrIsNull() {
            addCriterion("kurs_idr is null");
            return (Criteria) this;
        }

        public Criteria andKursIdrIsNotNull() {
            addCriterion("kurs_idr is not null");
            return (Criteria) this;
        }

        public Criteria andKursIdrEqualTo(Double value) {
            addCriterion("kurs_idr =", value, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrNotEqualTo(Double value) {
            addCriterion("kurs_idr <>", value, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrGreaterThan(Double value) {
            addCriterion("kurs_idr >", value, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrGreaterThanOrEqualTo(Double value) {
            addCriterion("kurs_idr >=", value, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrLessThan(Double value) {
            addCriterion("kurs_idr <", value, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrLessThanOrEqualTo(Double value) {
            addCriterion("kurs_idr <=", value, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrIn(List<Double> values) {
            addCriterion("kurs_idr in", values, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrNotIn(List<Double> values) {
            addCriterion("kurs_idr not in", values, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrBetween(Double value1, Double value2) {
            addCriterion("kurs_idr between", value1, value2, "kursIdr");
            return (Criteria) this;
        }

        public Criteria andKursIdrNotBetween(Double value1, Double value2) {
            addCriterion("kurs_idr not between", value1, value2, "kursIdr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transaksi
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 02 02:49:41 ICT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transaksi
     *
     * @mbg.generated Mon Jul 02 02:49:41 ICT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}